services:
  api:
    build: app
    container_name: fastapi-application
    environment:
      PORT: 80
    ports:
      - '80:80'
    volumes:
      - application_files:/tmp/test
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
  api1:
    build: app2
    container_name: fastapi-application1
    environment:
      PORT: 80
    ports:
      - '80:80'
    volumes:
      - application_files:/tmp/test
  volcopy:
    build: volume
    container_name: myvolume
    volumes:
      - application_files:/tmp/test
volumes:
  application_files:
