services:
  x-function: &function
    environment: 
      PORT: 80
      APP_ENV: dev
  api:
    <<: *function
    build: .
    container_name: fastapi-application
    ports:
      - '80:80'
#    volumes:
#      - application_files:/tmp/test
  cache:
    <<: *function
    environment:
      PORT: 6379
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
#volumes:
#  application_files:
