services:
  api:
    build: .
    container_name: fastapi-application
    environment:
      PORT: 80
    ports:
      - '80:80'
    deploy:
      mode: replicated
      replicas: 4
#    volumes:
#      - application_files:/tmp/test
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
#volumes:
#  application_files:
